In [27]:
import pandas as pd
from sqlalchemy import create_engine

### Load env variables

In [28]:
DATABASE_URL = 'postgresql://postgres.qjnlhsmfoaehsvswqeac:abdandwalaa@aws-0-eu-west-1.pooler.supabase.com:6543/postgres'

### Create POSTGRESQL connection

In [29]:

engine = create_engine(DATABASE_URL)

## Get the Raw Data from the properties table

In [30]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema='public'
"""

tables = pd.read_sql(query, engine)

tables

         table_name
0        properties
1  clean_properties

In [31]:
df = pd.read_sql("SELECT * FROM properties", engine)

df_clean = df.copy()

# Cleaning Phase

## Area

In [32]:
# Just a heads-up: when we’re cleaning the data, we won’t clean Area because it's already clean. However, there might be some work involved with it, and it really depends on the model we’re using. 

df_clean['area']

0       173.0
1       200.0
2       202.0
3       260.0
4       200.0
        ...
2057    180.0
2058    127.0
2059    176.0
2060    218.0
2061    238.0
Name: area, Length: 2062, dtype: float64

## Price

In [33]:
# Just a heads-up: when we’re cleaning the data, we won’t clean price because it's already clean. However, there might be some work involved with it, and it really depends on the model we’re using. 

df_clean['price']

0       13000000
1       12500000
2        3400000
3         250000
4       12500000
          ...
2057    15750000
2058     6500000
2059    13200000
2060    35000000
2061     9442832
Name: price, Length: 2062, dtype: int64

## Price per sqm

In [34]:
# create price_per_sqm from price and area

df_clean['price_per_sqm'] = df_clean['price'] / df_clean['area'].replace(0, pd.NA)

df_clean['price_per_sqm'].describe()
df_clean['price_per_sqm']

0        75144.508671
1        62500.000000
2        16831.683168
3          961.538462
4        62500.000000
            ...
2057     87500.000000
2058     51181.102362
2059     75000.000000
2060    160550.458716
2061     39675.764706
Name: price_per_sqm, Length: 2062, dtype: float64

## Baths

In [35]:
# convert to numeric
df_clean['baths'] = pd.to_numeric(
    df_clean['baths'],
    errors='coerce'
)

# impute using median inside each group
df_clean['baths'] = df_clean.groupby(
    ['property_type', 'area']
)['baths'].transform(
    lambda x: x.fillna(x.median())
)

# if any NaNs still exist -> drop them
df_clean = df_clean.dropna(subset=['baths'])
df_clean['baths']

0       3.0
2       3.0
5       2.0
8       2.0
9       1.0
       ...
2057    5.0
2058    2.0
2059    4.0
2060    3.0
2061    4.0
Name: baths, Length: 2047, dtype: float64

## Studio

In [36]:

# Detect studio apartments

df_clean['is_studio'] = (
    df_clean['beds']
    .astype(str)
    .str.contains('Studio', case=False, na=False)
)


# Convert Studio -> 0 
df_clean['beds'] = (
    df_clean['beds']
    .replace('Studio', 0)
)

df_clean['is_studio']

0       False
2       False
5       False
8       False
9       False
        ...
2057    False
2058    False
2059    False
2060    False
2061    False
Name: is_studio, Length: 2047, dtype: bool

## Beds

In [37]:
# Convert beds to numeric
df_clean['beds'] = pd.to_numeric(
    df_clean['beds'],
    errors='coerce'
)

# Group imputation
df_clean['beds'] = df_clean.groupby('property_type')['beds'].transform(
    lambda x: x.fillna(x.median())
)

df_clean['beds'] = df_clean['beds'].astype(int)

df_clean['beds']

0       3
2       4
5       2
8       3
9       1
       ..
2057    5
2058    3
2059    4
2060    3
2061    4
Name: beds, Length: 2047, dtype: int64

## Link 
### For now, we’re keeping the LINK up, but we’ll probably take it down if we need to.

In [38]:
df_clean['link']

0       https://www.dubizzle.com.eg/en/ad/lowest-downp...
2       https://www.dubizzle.com.eg/en/ad/apartment-fo...
5       https://www.dubizzle.com.eg/en/ad/apartment-fo...
8       https://www.dubizzle.com.eg/en/ad/apartment-16...
9       https://www.dubizzle.com.eg/en/ad/serviced-hot...
                              ...
2057    https://www.bayut.eg/en/property/details-50329...
2058    https://www.bayut.eg/en/property/details-50349...
2059    https://www.bayut.eg/en/property/details-50347...
2060    https://www.bayut.eg/en/property/details-50345...
2061    https://www.bayut.eg/en/property/details-50345...
Name: link, Length: 2047, dtype: str

## Source 
### For now, we’re keeping the SOURCE up, but we’ll probably take it down if we need to.

## Furnished

In [39]:
# Let’s change all the “nulls” in Furnishing to “Not Specified.”

df_clean['furnishing'] = (
    df_clean['furnishing']
    .fillna('Not Specified')
)

df_clean['furnishing']

0         Unfurnished
2       Not Specified
5         Unfurnished
8         Unfurnished
9           Furnished
            ...
2057      Unfurnished
2058      Unfurnished
2059      Unfurnished
2060      Unfurnished
2061      Unfurnished
Name: furnishing, Length: 2047, dtype: str

## Property type

In [40]:
# Normalize Property Type

# Remove extra spaces
# Standardize text casing
# Example:
# " apartment " -> "Apartment"

df_clean['property_type'] = (
    df_clean['property_type']
    .str.strip()
    .str.title()
)

print("Normalized property_type values:\n")
df_clean['property_type'].value_counts()

Normalized property_type values:

property_type
Apartment            1361
Villa                 358
Townhouse             105
Duplex                 81
Twin House             47
Penthouse              43
Ivilla                 25
Hotel Apartment        11
Studio                  4
Roof                    4
Room                    4
Other Residential       4
Name: count, dtype: int64

## Amenities

In [41]:
# Fill nulls with Not Mentioned 

df_clean['amenities'] = (
    df_clean['amenities']
    .fillna('Not Mentioned')
)

# Parsing Amenities and Extract new columns (Amenities count & Amenities List)

def parse_amenities(text):

    if pd.isna(text) or text == 'Not Mentioned':
        return []

    return [
        item.strip()
        for item in str(text).split(',')
        if item.strip()
    ]

# Convert amenities string -> list
df_clean['amenities_list'] = (
    df_clean['amenities']
    .apply(parse_amenities)
)

# Count amenities
df_clean['amenity_count'] = (
    df_clean['amenities_list']
    .apply(len)
)

df_clean[['amenities_list','amenity_count','amenities']]

,amenities_list,amenity_count,amenities
0,"[Balcony, Private Garden, Security, Pool]",4,"Balcony, Private Garden, Security, Pool"
2,"[Private Garden, Pool, Electricity Meter, Wate...",5,"Private Garden, Pool, Electricity Meter, Water..."
5,"[Balcony, Private Garden, Security, Covered Pa...",9,"Balcony, Private Garden, Security, Covered Par..."
8,[],0,Not Mentioned
9,[],0,Not Mentioned
...,...,...,...
2057,[],0,Not Mentioned
2058,[],0,Not Mentioned
2059,[],0,Not Mentioned
2060,[],0,Not Mentioned
2061,[],0,Not Mentioned

## Transaction type

In [42]:
# Parse transaction type

df_clean['transaction_type'] = (
    df_clean['link']
    .str.contains('for-rent', case=False, na=False)
    .map({True: 'rent', False: 'sale'})
)

# Keeping only Sale Transactions and drop rent ones 
df_clean = df_clean[df_clean["transaction_type"] == "sale"]

df_clean['transaction_type']

0       sale
2       sale
5       sale
8       sale
9       sale
        ...
2057    sale
2058    sale
2059    sale
2060    sale
2061    sale
Name: transaction_type, Length: 2047, dtype: str

## Location

In [43]:
# Just a heads-up: during the cleaning step, we’re not cleaning the location because it’s already clean. However, the amount of work involved might vary quite a bit depending on the model type.

df_clean['location']

0           Palm Hills New Cairo Compound, 5th Settlement
2                             Al Andalous, 5th Settlement
5            Hyde Park New Cairo Compound, 5th Settlement
8                                     Wesal, Shorouk City
9                                      Reve du nil, Maadi
                              ...
2057    El Patio Compound, 5th Settlement, New Cairo, ...
2058                         Rehab City, New Cairo, Cairo
2059            Azzar 2, 5th Settlement, New Cairo, Cairo
2060    Mivida Compound, 5th Settlement, New Cairo, Cairo
2061                   Bloomfields, Mostakbal City, Cairo
Name: location, Length: 2047, dtype: str

## City & District (Created out of Location)

In [44]:
# Extract district and city from location

# Split location into parts
location_parts = df_clean['location'].str.split(',')

# First part → district / compound
df_clean['district'] = (
    location_parts
    .str[0]
    .str.strip()
)

# Last part → city
df_clean['city'] = (
    location_parts
    .str[-1]
    .str.strip()
)

df_clean[['location', 'district', 'city']]

,location,district,city
0,"Palm Hills New Cairo Compound, 5th Settlement",Palm Hills New Cairo Compound,5th Settlement
2,"Al Andalous, 5th Settlement",Al Andalous,5th Settlement
5,"Hyde Park New Cairo Compound, 5th Settlement",Hyde Park New Cairo Compound,5th Settlement
8,"Wesal, Shorouk City",Wesal,Shorouk City
9,"Reve du nil, Maadi",Reve du nil,Maadi
...,...,...,...
2057,"El Patio Compound, 5th Settlement, New Cairo, ...",El Patio Compound,Cairo
2058,"Rehab City, New Cairo, Cairo",Rehab City,Cairo
2059,"Azzar 2, 5th Settlement, New Cairo, Cairo",Azzar 2,Cairo
2060,"Mivida Compound, 5th Settlement, New Cairo, Cairo",Mivida Compound,Cairo
2061,"Bloomfields, Mostakbal City, Cairo",Bloomfields,Cairo

## City & District with unknown as default (Created out of Location)

In [45]:
# Extract district and city from location

KNOWN_CITIES = [
    'Cairo',
    'Giza',
    'Alexandria',
    'New Cairo',
    'New Capital City'
]

def parse_location(location):

    if pd.isna(location):
        return pd.NA, pd.NA

    parts = [p.strip() for p in location.split(',')]

    # First part usually compound / district
    district = parts[0]

    # Default
    city = 'Unknown'

    # Search for known cities
    for part in parts:
        if part in KNOWN_CITIES:
            city = part
            break

    return district, city


df_clean[['district', 'city']] = (
    df_clean['location']
    .apply(parse_location)
    .apply(pd.Series)
)

df_clean[['district', 'city']]

                           district       city
0     Palm Hills New Cairo Compound    Unknown
2                       Al Andalous    Unknown
5      Hyde Park New Cairo Compound    Unknown
8                             Wesal    Unknown
9                       Reve du nil    Unknown
...                             ...        ...
2057              El Patio Compound  New Cairo
2058                     Rehab City  New Cairo
2059                        Azzar 2  New Cairo
2060                Mivida Compound  New Cairo
2061                    Bloomfields      Cairo

[2047 rows x 2 columns]

## Drop Columns 

### Just a heads-up: these columns aren’t really useful for building or improving machine learning models, so we’ve decided to remove them based on this reason .

## ID (drop)

In [46]:
df_clean = df_clean.drop(columns=['id'])

## Checksum (drop)

In [47]:
df_clean = df_clean.drop(columns=['checksum'])

## Title (drop)

In [48]:
df_clean = df_clean.drop(columns=['title'])

## Reactivated date (drop)

In [49]:
df_clean = df_clean.drop(columns=['reactivated_date'])

## Scraped at (drop)

In [50]:
df_clean = df_clean.drop(columns=['scraped_at'])

## Transformed at (drop)

In [51]:
df_clean = df_clean.drop(columns=['transformed_at'])

# Save the new Clean Data to a new table (clean properties) in the postgres db

In [52]:
df_clean.to_sql(
    name='clean_properties',
    con=engine,
    if_exists='replace',
    index=False
)

47